### ISSUE TITLE
🔨 [Refactoring] layout 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#102]
### Description

기존의  `GComponent` 를 `styled-components` 의 as 로 변경
+ `Grid` 컴포넌트 추가

### Todo

- [ ] `GComponent` 삭제
- [ ] `Box` 컴포넌트 리팩토링
- [ ] `Button` 컴포넌트 리팩토링
- [ ] `Grid` 컴포넌트 구현
