### ISSUE TITLE
✨ [Feature] unregistered 유저의 로그인

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#129]
### Description
- nickname 초기 설정을 하지 않아 `user` table에 존재하지 않은 `unregistered` 상태의 유저 로그인

### Todo
- [x] unregistered 유저가 로그인하는 경우 nickname 초기 설정 페이지로 redirect
- [x] 처음 로그인하는 유저 auth table data 생성
- [x] unregistered 유저가 닉네임 초기 설정 완료하면, 기존 token Cookie에서 삭제, 새로운 token 발급 (`createUser`에서 처리)
- [x] 완료후 로비 페이지로 redirect
