### ISSUE TITLE
✨ [Feature] token 관련한 guard 적용시키기

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#138]
### Description
- token에 담겨져있는 `userId` 반환하는 custom decorator 만들고 적용시키기

### Todo
- [x] token에서 userId 반환하는 custom decorator(`@ExtractUserId`) 생성
- [x] guard 만들어서 `@UseGuards(AuthGuard'ft')` 대신 `@UseGuards(FtGuard)`와 같이 사용
- [x] `@Headers` 대신 `@ExtractUserId`로 수정
- [x]  `UserGuard` skip하는 guard 생성
- [x] 개발 단계에서 사용할 guard 막아주는 로직 추가
- [x] 개발 단계에서 사용할 Headers `ExtractUserId`에 추가
