### ISSUE TITLE
✨ [Feature] Friend API 수정

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#186]
### Description

- 친구 신청한 리스트 가져오는 api
  - `friendId` 도 포함시켜서 response
- 친구 신청을 수락, 거절하는 api
- 친구 삭제하는 api
  - path parameter 를 `userId`  ->  `friendId`로 변경

### Todo
- [x] `GET /friend/request`
- [x] `POST /friend/reject/{friendId}`
- [x] `POST /friend/accept/{friendId}`
- [x] `DELETE /friend/{friendId}`
