### ISSUE TITLE
✨ [Feature] login 시 online 상태 보내는 웹소켓 API

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#222]
### Description

- login 직후 `connect` 되었을 때 일어나야 하는 웹소켓 이벤트들을 구현합니다.

### Todo

- [x] `connect` 한 client 의 id 를 이용해서 room 생성 후 접속 중인 친구의 socket 을 `join()`
- [x] 생성된 room 에 `online` 이벤트 broadcast
- [x] 접속 중인 친구의 room 을 찾아 나의 socket 을 `join()`
