### ISSUE TITLE
✨ [Feature] private channel 참여 로직 추가

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#337]
### Description

- private channel 참여하는 로직 추가

### Todo
- [x] #340
- [x] 채널 참여하기할 때 '게임중' 상태인지 확인 필요
- [x] private mode channel에서 초대받은 유저인지 확인하는 로직 추가
- [x] channel model에 status 추가
