### ISSUE TITLE
✨ [Feature] 친구 관련 업적 구현하기 

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#461]
### Description

친구 관련 업적 구현하기 

### Todo

- [ ] 업적 5번 : 첫 친구 만들어 봤을 때 -> 드디어 친구가 생겼어요!!
- [ ] 업적 6번 : 친구 10명 		       -> 인싸로 가는 첫 걸음!!
- [ ] 업적 7번 : 친구 42명 		       -> 당신은 마당발!!
