### ISSUE TITLE
🔨 [Refactoring] dev 환경설정 수정

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#581]
### Description

개발 단계에서 사용할 db script 수정

### Todo
 - [ ] dev Dockerfile 분리
 - [ ] dev docker compose 분리
 - [ ] backend script 수정
