### ISSUE TITLE
🔨 [Refactoring] 환경분리

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#600]
### Description

`local`
- 로컬환경에서 실행할 때
- [ ] x-my-id 밖에 안되서 `x-my-id` -> `42oauth` 가능하도록 수정 (localhost 등록되어있는지 확인)
- [ ] FE, BE 둘다 `Dockerfile.local` 생성
- [ ] `docker-compose.local.yml` 생성

`dev`
- development 서버에서 실행할 때 / 어떻게 띄울지 논의필요함 (인스턴스 or 포트)
- [ ] 42login 가능하도록 설정, 디비 볼륨 따로 분리 (포트)
- [ ] 42Application 에 dev server 등록
- [ ] `docker-compose.dev.yml` 생성

`prod`
- 실제 배포된 서버일 때
- `Dockerfile.prod` 생성
- `docker-compose.prod.yml` 생성

### Todo

- [ ] local
- [ ] dev
- [ ] prod
